# Generated by Django 3.0.3 on 2020-04-28 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField()),
                ('sname', models.CharField(max_length=100)),
                ('sage', models.IntegerField()),
                ('sdepartment', models.CharField(max_length=100)),
                ('ssubject', models.TextField(default='[]')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
